version: '3.7'

name: brainstorm
services:
  mongo:
    image: "mongodb/mongodb-community-server"
    container_name: brainstorm-mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - whiteboard-backend

networks:
  whiteboard-backend: